from github import Github
import os

import time

class GitHubIntegration:
    def __init__(self, config=None, token=None, repo_name=None):
        '''Initialize GitHub client.
        
        Args:
            config: Config object (preferred)
            token: GitHub personal access token (deprecated)
            repo_name: Repository name (deprecated)
        '''
        if config:
            self.config = config
            if not config.github.enable_github:
                raise ValueError("GitHub integration is disabled in configuration")
            self.client = Github(config.github.token)
            self.repo = self.client.get_repo(config.github.repo_name)
        elif token and repo_name:
            self.client = Github(token)
            self.repo = self.client.get_repo(repo_name)
        else:
            raise ValueError("Either config or token/repo_name must be provided")
    
    def create_healing_pr(self, file_path, fixed_code, error_log, attempt_count):
        '''Create a Pull Request with the AI-generated fix.'''
        # Create a new branch
        branch_name = f'auto-heal-{int(time.time())}'
        base_branch = self.repo.default_branch
        sb = self.repo.get_branch(base_branch)
        self.repo.create_git_ref(ref=f'refs/heads/{branch_name}', sha=sb.commit.sha)
        
        # Get the file
        file_rel_path = file_path.replace('E:\\\\self_healing_pipeline\\\\', '').replace('\\\\', '/')
        contents = self.repo.get_contents(file_rel_path, ref=base_branch)
        
        # Update the file
        commit_message = f' Auto-heal: Fix schema drift (Attempt {attempt_count})'
        self.repo.update_file(
            contents.path,
            commit_message,
            fixed_code,
            contents.sha,
            branch=branch_name
        )
        
        # Create PR
        pr_title = f' Auto-Heal: Schema Drift Fix'
        pr_body = f'''## Automated Fix by Data Doctor

**Error Log:**
`
{error_log[:500]}
`

**Healing Attempts:** {attempt_count}

**Status:**  Fix tested and validated

This PR was automatically generated by the Self-Healing Pipeline system.
Please review the changes before merging.
'''
        
        pr = self.repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=base_branch
        )
        
        print(f' Pull Request created: {pr.html_url}')
        return pr.html_url

if __name__ == '__main__':
    print('GitHub Integration module loaded.')
